[tool.poetry]
name = "monitoring-service"
version = "0.1.0"
description = "A service responsible for providing monitoring data."
authors = ["Renato Teixeira <rena2damas@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "*", from = "src" }
]
homepage = ""
repository = "https://github.com/rena2damas/monitoring-service"
documentation = ""
keywords = [
    "monitoring",
    "swagger",
    "openapi",
    "oas3",
    "rest",
    "api",
    "web",
    "flask",
    "python",
    "python3"
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10"
]

[tool.poetry.dependencies]
aenum = "^3.0.0"
apispec = { extras = ["yaml"], version = "^5.0.0" }
apispec-plugins = "^0.1.0"
environs = "^9.0.0"
flasgger = "^0.9.0"
Flask = "^2.0.0"
Flask-RESTful = "*"
Flask-SQLAlchemy = "^2.0.0"
python = "^3.7"
requests = "^2.0.0"
urllib3 = "^1.0.0"

[tool.poetry.dev-dependencies]
coverage = "^6.0.0"
pre-commit = "^2.0.0"
pytest = "^7.0.0"
pytest-mock = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
