---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: monitoring-api
spec:
  rules:
    - host: services.com
      http:
        paths:
          - path: /api/monitoring/v1
            backend:
              serviceName: monitoring-api
              servicePort: 80